Doctor 2278330
odoo-ps/psae-Fourth-Dimension-Medical pull request #16
Opened 2021-01-19 11:47 UTC by ary-odoo

2021-01-19 11:55 UTC, bakboka requested changes

2021-01-19 11:55 UTC, bakboka commented on fdmc/models/pos.py
> +            'doctor_id': ui_order.get('doctor', False).get('id') if ui_order.get('doctor', False) is not None else False
you have a case where this will throw an error. If ui_order.get('doctor', False) returns False, which is the value returned when the key does not exist, then the if will be true and you will try to use the get function on a boolean thus a traceback. I think you mean to do "if ui_order.get('doctor', False)"
None is evaluated as False so it will go to the else

2021-01-20 15:01 UTC, ary-odoo commented on fdmc/models/pos.py
> +            'doctor_id': ui_order.get('doctor', False).get('id') if ui_order.get('doctor', False) is not None else False
the reason for this is that even if the 'doctor' field has no value from the frontend, it will be part of the dictionary, and will have a value of None.
so I don't need the 'get' function, I will do a clean up

2021-01-24 05:56 UTC, bakboka approved these changes

2021-01-24 06:13 UTC, merged